Repository creek-service/json-schema-validation-comparison, pull requests merged in 2023-11, with the labels that each got.

#46 Generate JSON document listing tested implementations
  README.md
  build.gradle.kts
  src/main/java/org/creekservice/kafka/test/perf/ImplementationsMain.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/PerDraftSummary.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/Summary.java
  src/main/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatter.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
Labels: enhancement

#48 Data driven documentation on implementations under test
  .github/workflows/gh-pages.yml
  build.gradle.kts
  docs/.gitignore
  docs/Gemfile
  docs/README.md
  docs/_config.dev.yml
  docs/_config.yml
  docs/_data/navigation/docs.yml
  docs/_docs/1. implementations.md
  docs/assets/images/json.png
  src/main/java/org/creekservice/kafka/test/perf/implementations/ConfluentImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/EveritImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JacksonImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JustifyImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/MedeiaImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/NetworkNtImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SchemaFriendImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SkemaImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SnowImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/VertxImplementation.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
Labels: enhancement

#49 Fix gh-pages.yml
  .github/workflows/gh-pages.yml
Labels: bug

#54 Data driven functional test results
  .github/workflows/gh-pages.yml
  .github/workflows/run-func-test.yml
  README.md
  build.gradle.kts
  docs/_docs/0. home.md
  docs/_docs/1. implementations.md
  docs/_docs/2. functional.md
  docs/_docs/3. performance.md
  src/main/java/org/creekservice/kafka/test/perf/FunctionalMain.java
  src/main/java/org/creekservice/kafka/test/perf/ImplementationsMain.java
  src/main/java/org/creekservice/kafka/test/perf/PerformanceMain.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/ConfluentImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JacksonImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JustifyImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/MedeiaImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/NetworkNtImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SchemaFriendImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SkemaImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SnowImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/VertxImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonValidateBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/PerDraftSummary.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/Summary.java
  src/main/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatter.java
  src/main/java/org/creekservice/kafka/test/perf/util/Table.java
  src/main/java/org/creekservice/kafka/test/perf/util/TestSchemas.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/ImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
Labels: enhancement

#50 Feature/dev harrel impl
  build.gradle.kts
  src/main/java/org/creekservice/kafka/test/perf/implementations/DevHarrelImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementations.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonValidateBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/TestSuite.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/TestSuiteLoader.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/DevHarrelImplementationTest.java
Labels: enhancement

#62 Data driven performance results
  .github/workflows/gh-pages.yml
  .github/workflows/run-perf-test.yml
  README.md
  build.gradle.kts
  docs/.gitignore
  docs/README.md
  docs/_docs/1. implementations.md
  docs/_docs/2. functional.md
  docs/_docs/3. performance.md
  img/Feature-comparison-score.svg
  img/JsonSerdeBenchmark-Results.svg
  img/JsonValidateBenchmark-Draft-2019-0.svg
  img/JsonValidateBenchmark-Draft-2020-12.svg
  img/JsonValidateBenchmark-Draft-4.svg
  img/JsonValidateBenchmark-Draft-6.svg
  img/JsonValidateBenchmark-Draft-7.svg
  src/main/java/org/creekservice/kafka/test/perf/FunctionalMain.java
  src/main/java/org/creekservice/kafka/test/perf/ImplementationsMain.java
  src/main/java/org/creekservice/kafka/test/perf/PerformanceMain.java
  src/main/java/org/creekservice/kafka/test/perf/ProjectPaths.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/ConfluentImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/DevHarrelImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/EveritImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementations.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JacksonImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SkemaImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/VertxImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonValidateBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/performance/util/JsonToMarkdownConvertor.java
  src/main/java/org/creekservice/kafka/test/perf/performance/util/PerformanceDataValidator.java
  src/main/java/org/creekservice/kafka/test/perf/performance/util/PerformanceJsonReader.java
  src/main/java/org/creekservice/kafka/test/perf/performance/util/model/Metric.java
  src/main/java/org/creekservice/kafka/test/perf/performance/util/model/PerformanceResult.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/SchemaSpec.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/PerDraftSummary.java
  src/test/java/org/creekservice/kafka/test/perf/performance/util/JsonToMarkdownConvertorTest.java
  src/test/java/org/creekservice/kafka/test/perf/performance/util/PerformanceDataValidatorTest.java
  src/test/java/org/creekservice/kafka/test/perf/performance/util/PerformanceJsonReaderTest.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
Labels: enhancement

#64 Add summary / other considerations page
  docs/_data/navigation/docs.yml
  docs/_docs/4. other considerations.md
Labels: enhancement

#63 Include DRAFT 2020-12 to serde benchmark
  README.md
  config/spotbugs/suppressions.xml
  docs/_docs/3. performance.md
  src/main/java/org/creekservice/kafka/test/perf/PerformanceMain.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/DevHarrelImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JacksonImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JustifyImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/SchemaFriendImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
Labels: enhancement

#68 Include minimum Java version supported by implementations
  build.gradle.kts
  docs/_docs/1. implementations.md
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/util/ImplJarFile.java
  src/main/java/org/creekservice/kafka/test/perf/util/JarFile.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplJarFileTest.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
  src/test/java/org/creekservice/kafka/test/perf/util/JarFileTest.java
Labels: enhancement

#67 Generate unit tests for new implementations automagically.
  README.md
  src/test/java/org/creekservice/kafka/test/perf/implementations/DevHarrelImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/EveritImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/ImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/JacksonImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/JustifyImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/MedeiaImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/NetworkNtImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/SchemaFriendImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/SkemaImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/SnowImplementationTest.java
  src/test/java/org/creekservice/kafka/test/perf/implementations/VertxImplementationTest.java
Labels: enhancement

#66 Report Jar version
  build.gradle.kts
  config/spotbugs/suppressions.xml
  docs/_docs/1. implementations.md
  docs/_docs/4. other considerations.md
  src/main/java/org/creekservice/kafka/test/perf/implementations/Implementation.java
  src/main/java/org/creekservice/kafka/test/perf/implementations/JustifyImplementation.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/util/ImplJarFile.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplJarFileTest.java
  src/test/java/org/creekservice/kafka/test/perf/util/ImplsJsonFormatterTest.java
Labels: enhancement

#71 Remove snow from validation benchmark charts
  docs/_docs/3. performance.md
Labels: enhancement

#74 Reduce thread-count in benchmarks
  README.md
  buildSrc/src/main/kotlin/creek-plugin-publishing-convention.gradle.kts
  buildSrc/src/main/kotlin/creek-publishing-convention.gradle.kts
  docs/_docs/3. performance.md
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonSerdeBenchmark.java
  src/main/java/org/creekservice/kafka/test/perf/performance/JsonValidateBenchmark.java
Labels: enhancement

#80 Minor doc improvements
  docs/_docs/1. implementations.md
  docs/_docs/2. functional.md
  docs/_docs/3. performance.md
  docs/_docs/4. other considerations.md
  src/main/java/org/creekservice/kafka/test/perf/FunctionalMain.java
  src/main/java/org/creekservice/kafka/test/perf/testsuite/output/Summary.java
Labels: enhancement

#83 Add windows build
  .github/workflows/build.yml
Labels: chore

#85 Update to the latest build conventions.
  .github/workflows/build.yml
  buildSrc/src/main/kotlin/creek-common-convention.gradle.kts
Labels: chore
